### ISSUE TITLE
Implement Relaton for IEEE documents

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ieee#1]

**Comment by andrew2net** [comment]
@ronaldtse do we have a mapping for IEEE documents?

<img width="590" alt="image" src="https://user-images.githubusercontent.com/5623890/80634555-ee6c8300-8a5a-11ea-960a-ea388d02707e.png">

**Comment by opoudjis** [comment]
Andrej, do you want help assigning the roles in what you've copy-pasted to relaton?

**Comment by andrew2net** [comment]
@opoudjis yes Nick, can you help?

**Comment by opoudjis** [comment]
Sure, will do tonight.

**Comment by opoudjis** [comment]
Sponsor Committee: `ext/committee[@type = 'sponsor']/name`

Status: `status/stage`

Board approval: `date[@type = 'issued']`

History: Published Date: `date[@type = 'published']`

PAR: Each PAR link (Project Authorization Request) links to a page full of metadata for the record; e.g. https://development.standards.ieee.org/myproject-web/public/view.html#pardetail/6463. Consider how much of this added metadata you actually need.

Working Group: `ext/committee[@type = 'working']/name`

Working Group Chair: `ext/committee[@type = 'working']/chair`

Sponsor Committee: `ext/committee[@type = 'sponsor']/name`

Society: `ext/committee[@type = 'society']/name`

IEEE Program Manager: `contributor[role/@type = 'compiler'][role = 'program manager']/person/name

@ronaldtse will need to approve.

**Comment by ronaldtse** [comment]
This list looks fine with me, please also help update https://github.com/relaton/relaton-model-ieee/issues/1 . Thanks!
