### ISSUE TITLE
Conversion to BibXML introduces duplicated publisher in anchor

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ieee#11]
From @kesera:

https://github.com/ietf-ribose/bibxml-service/issues/31#issue-1070001720

> The `reference` `anchor` attribute data is different: `anchor="IEEE.802.11_2012"` vs `anchor="IEEE.IEEE 802-11.2012"`

1. The anchor is to be read by machines. It should not contain any empty spaces.
2. The correct anchor here should be something like "IEEE.802-11_2012", depending on the IEEE PubId scheme.

**Comment by andrew2net** [comment]
@ronaldtse now all anchors are the same as they in the data source https://github.com/ietf-ribose/bibxml-data-ieee/blob/main/data/802-11.2012.xml
