### ISSUE TITLE
Title with `text/plain` format should not contain HTML entities

### ISSUE THREAD

**Issue by strogonoff** [relaton/relaton-ieee#22]
Example: https://github.com/ietf-tools/relaton-data-ieee/blob/95b53bb269d5f069213efc87c53e9e49c5dfb345/data/IEEE_802-11.2016.yaml#L4-L9

I don’t know whether it’s best to remove HTML entities, or to change title format🤔

**Comment by ronaldtse** [comment]
Let's convert out these HTML entities to text/plain if possible.
