### ISSUE TITLE
Proper document identifier for IEEE_802-15-4J.2013.yaml is "IEEE 802.15.4j-2013"

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ieee#24]
The data generated is inaccurate in this regard.

https://github.com/ietf-tools/relaton-data-ieee/blob/8f660a6a5eecaefe6185ce75e50222af640d098c/data/IEEE_802-15-4J.2013.yaml#L15

Which says:
```yaml
- id: IEEE 802-15-4j.2013
```

**Comment by andrew2net** [comment]
@ronaldtse is this issue related to all the IEEE identifiers or just `EEE 802-15-4j.2013`? Because the gem renders all numbers, parts, and subparts separated with a dash, and years separated with a period.

**Comment by ronaldtse** [comment]
I suppose this is related to all IEEE identifiers, where this is only a single instance of the problem.

The proper IEEE identifier should look like this: "IEEE Std 802.15.4j-2013". pubid-ieee should be able to normalise the identifier properly.

**Comment by andrew2net** [comment]
Fixed but the relaton-data-iee will update on the next cron running.
