### ISSUE TITLE
Mapping of IEEE contributors in bibliographic data

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ieee#27]
```sh
$ bundle exec relaton fetch "IEEE 2830"
```

```xml
<bibitem id="IEEE2830-2021">
  <fetched>2022-07-12</fetched>
  <title type="main" format="text/plain" language="en" script="Latn">IEEE Standard for Technical Framework and Requirements of Trusted Execution Environment based Shared Machine Learning</title>
  <uri type="src">https://standards.ieee.org/ieee/2830/10231/</uri>
  <docidentifier type="IEEE" primary="true">IEEE 2830-2021</docidentifier>
  <date type="issued">
    <on>2021-06-16</on>
  </date>
  <date type="published">
    <on>2021-10-22</on>
  </date>
  <contributor>
    <role type="author"/>
    <person>
      <name>
        <completename>Christy Bahn</completename>
      </name>
    </person>
  </contributor>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>Institute of Electrical and Electronics Engineers</name>
      <abbreviation>IEEE</abbreviation>
      <address>
        <street>445 Hoes Lane</street>
        <city>Piscataway</city>
        <state>NJ</state>
        <country>USA</country>
        <postcode>08854-4141</postcode>
      </address>
    </organization>
  </contributor>
  <language>en</language>
  <script>Latn</script>
  <abstract format="text/plain" language="en" script="Latn">The framework and architecture for machine learning in which a model is trained using encrypted data that has been aggregated from multiple sources and is processed by a trusted third party are defined in this standard. Functional components, workflows, security requirements, technical requirements, and protocols are specified in this standard.</abstract>
  <status>
    <stage>Active</stage>
  </status>
  <place>Piscataway, NJ, USA</place>
</bibitem>
```

On the official page:
https://standards.ieee.org/ieee/2830/10231/

<img width="710" alt="Screenshot 2022-07-13 at 12 40 10 AM" src="https://user-images.githubusercontent.com/11865/178532071-185d7500-3624-43b7-a54e-d1a9cff60e7f.png">

Note that "Christy Bahn" is actually the "IEEE Program Manager", which is not really a contributor and definitely not the "author". There is no "author" provided in the data.

I wonder where the information "Christy Bahn" came from -- I thought this was from ieee-rawbib?

In `ieee-rawbib` data, we should add these as well:

Add ISBN information:
```xml
    <isbn isbntype="New-2005" mediatype="Electronic">978-1-5044-7724-6</isbn>
```

Add Sponsoring Committee:
```xml
    <pubsponsoringcommitteeset>
      <pubsponsoringcommittee><![CDATA[Artificial Intelligence Standards Committee of the IEEE Computer Society]]></pubsponsoringcommittee>
    </pubsponsoringcommitteeset>
```

**Comment by andrew2net** [comment]
> I wonder where the information "Christy Bahn" came from -- I thought this was from ieee-rawbib?

@ronaldtse relaton-ieee still use https://standards.ieee.org/search to fetch documents. Should we switch to https://github.com/relaton/relaton-data-ieee?

**Comment by ronaldtse** [comment]
> Where should we save the committee in the Relaton IEEE model? `editorialgroup/committee`?

Yes. 

We should also migrate the IEEE models into https://github.com/metanorma/metanorma-model-ieee .

**Comment by andrew2net** [comment]
@ronaldtse from the version 1.12.5 this gem fetches documents from the `relaton-data-ieee` repo, so the documents have ISBN identifiers and contributors as in the source.

The `editorialgroup/committee` element is rendered inside the `ext` element, but the `relaton-cli` renders output as `bibitem`. Only documents rendered as `bibdata` have flavor specified `ext` element. I don't know why the `relator-cli` outputs documents in basic form, not flavor specific. Should we update `relaton-cli` to output `bibdata`?

Since the `relaton-ieee` fetches documents from the `relaton-data-ieee` we have to use references that match files in the source repo (`IEEE 2830-2021` not `IEEE 2830`). Do we need to implement indexing to be able using partly matching references?

**Comment by ronaldtse** [comment]
> I don't know why the relator-cli outputs documents in basic form, not flavor specific. Should we update relaton-cli to output bibdata?

Yes I think so, let's file a ticket there.

> Since the relaton-ieee fetches documents from the relaton-data-ieee we have to use references that match files in the source repo (IEEE 2830-2021 not IEEE 2830). Do we need to implement indexing to be able using partly matching references?

Yes:
1. This is the undated vs dated reference difference. We need to support that as well.
2. In addition, we need to support the full identifier "IEEE Std 2830" vs "IEEE 2830". Let's use `pubid-ieee` to resolve this.

**Comment by andrew2net** [comment]
@ronaldtse can we close this issue?

**Comment by ronaldtse** [comment]
Yes we can. Thanks @andrew2net ! I will raise this issue with IEEE officially.
