### ISSUE TITLE
Support full and partial identifiers: "IEEE Std 2830" vs "IEEE 2830"

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ieee#30]
We need to support the full identifier "IEEE Std 2830" vs "IEEE 2830".

We should use `pubid-ieee` to handle this.

_Originally posted by @ronaldtse in https://github.com/relaton/relaton-ieee/issues/27#issuecomment-1196221667_

**Comment by andrew2net** [comment]
> We need to support the full identifier "IEEE Std 2830" vs "IEEE 2830".

@ronaldtse the relaton-ieee supports references with "Std" already.

> We should use `pubid-ieee` to handle this.

It seems the `pubid-ieee` handles only IEEE publisher but in the `ieee-rawbib` dataset there are many others (AIEE, ANSI, IEC, IEC/IEEE, IRE, ISO/IEC, ISO/IEC/IEEE, ISO/IEEE, NACE, NACE/IEEE, USAS). Do we need to support all these publishers?
