### ISSUE TITLE
(URGENT) Structural discrepancies in Relaton-IEEE data files

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ieee#32]
From https://github.com/relaton/relaton/issues/108

There are structural discrepancies reported by @strogonoff.

>  * [IEEE](https://raw.githubusercontent.com/ietf-tools/relaton-data-ieee/main/data/ANSI_IEEE_991-1986.yaml):
> 
> ```
> contributor -> 0 -> organization -> abbreviation
>   str type expected (type=type_error.str)
> keyword
>   str type expected (type=type_error.str)
> keyword -> 0
>   str type expected (type=type_error.str)
> copyright -> 0 -> owner -> 0 -> name -> 0
>   str type expected (type=type_error.str)
> copyright -> 0 -> owner -> 0 -> name
>   str type expected (type=type_error.str)
> copyright -> 0 -> owner -> 0 -> abbreviation
>   str type expected (type=type_error.str)
> copyright -> from
>   field required (type=value_error.missing)
> copyright -> owner
>   value is not a valid list (type=type_error.list)
> ```

**Comment by ronaldtse** [comment]
Reported by @alicerusso at https://github.com/ietf-tools/bibxml-service/issues/283#issuecomment-1282855417:

- https://bib.ietf.org/get-one/by-docid/?doctype=IEEE&docid=IEEE+1003.1-2017&format=bibxml
- https://bib.ietf.org/get-one/by-docid/?doctype=IEEE&docid=IEEE+1003.1-2016&format=bibxml
- https://bib.ietf.org/get-one/by-docid/?doctype=IEEE&docid=IEEE+802.1Q-2014&format=bibxml

> Could not export this item, the error was: Source data for item IEEE 1003.1-2017 (IEEE) didn’t validate (err: 7 validation errors for BibliographicItem copyright -> 0 -> owner -> 0 -> name -> 0 str type expected (type=type_error.str) copyright -> 0 -> owner -> 0 -> name str type expected (type=type_error.str) copyright -> 0 -> owner -> 0 -> abbreviation str type expected (type=type_error.str) copyright -> 0 -> owner -> 1 -> name -> 0 str type expected (type=type_error.str) copyright -> 0 -> owner -> 1 -> name str type expected (type=type_error.str) copyright -> from value is not a valid integer (type=type_error.integer) copyright -> owner field required (type=value_error.missing))

the last one:
> Could not export this item, the error was: Source data for item IEEE 802.1Q-2014 (IEEE) didn’t validate (err: 5 validation errors for BibliographicItem copyright -> 0 -> owner -> 0 -> name -> 0 str type expected (type=type_error.str) copyright -> 0 -> owner -> 0 -> name str type expected (type=type_error.str) copyright -> 0 -> owner -> 0 -> abbreviation str type expected (type=type_error.str) copyright -> from value is not a valid integer (type=type_error.integer) copyright -> owner field required (type=value_error.missing))

**Comment by andrew2net** [comment]
@ronaldtse we had structure simplification in the YAML output, so instances of LocalizedString or FormattedRef could be rendered as strings in case only content is present. This caused inconsistency in YAML output. Now all instances of the classes are rendered as objects, so the bibxml-service should adopt the format.
As per https://github.com/relaton/relaton/issues/108#issuecomment-1288150738 many of these issues were fixed in the relaton-py.

**Comment by andrew2net** [comment]
```
copyright -> from
  field required (type=value_error.missing)
```
The attribute `from` is present in the [IEEE document](https://raw.githubusercontent.com/ietf-tools/relaton-data-ieee/main/data/ANSI_IEEE_991-1986.yaml)
