### ISSUE TITLE
(URGENT) IEEE data fetch failure from ietf-tools/ieee-rawbib

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ieee#34]
It looks like the validation of stage values is causing crashes in the daily fetch job.

https://github.com/ietf-tools/relaton-data-ieee/actions/runs/3621385071/jobs/6104755061

<img width="1234" alt="Screen Shot 2022-12-06 at 12 25 00 AM" src="https://user-images.githubusercontent.com/11865/205688830-c1727e0f-5537-4a7b-9b22-83dc48dc8016.png">

**Comment by andrew2net** [comment]
@ronaldtse there is a document in the ieee-rawbib source
`ieee-rawbib/cache/IEEEstd/1993/7438944/7438945/07438946.xml`
with the "Nuclear EQ Sourcebook and Supplement" normtitle. We parse normtitles to have parts of document's identifier. It seems that this normtitle doesn't have any parts of identifier. How should we handle such documents?

**Comment by ronaldtse** [comment]
@andrew2net I think there are only a few of these documents. I prefer that we manually name their identifiers with their IEEE publication identifier:

<img width="625" alt="Screen Shot 2022-12-17 at 7 25 00 AM" src="https://user-images.githubusercontent.com/11865/208198893-e9416a8b-efbe-4671-9bb7-4f8a8f266641.png">

Which is `7438946`. Let's call this `IEEE 7438946` for now.
