### ISSUE TITLE
Add support of location syntax in form of "IEEE Std 1619-2007"

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ieee#5]
Metanorma autofetch:
```
* [[[AES-XTS,IEEE Std 1619-2007]]]
```

AsciiBib
```
[%bibitem]
=== The XTS-AES Tweakable Block Cipher
id:: AES-XTS
docid::
  id::: AES-XTS
contributor::
contributor.role:: author
contributor.person.name.surname:: IEEE Std
contributor.person.affiliation.organization.name:: IEEE
contributor::
contributor.role:: publisher
contributor.organization.name:: Institute of Electrical and Electronics Engineers, Inc.
contributor.organization.abbreviation:: IEEE
date::
date.type:: published
date.value:: 2008
```

**Comment by ronaldtse** [comment]
```
* [[[AES-XTS,IEEE Std 1619-2007]]]
```

Doesn't work.

```
* [[[AES-XTS,IEEE 1619-2007]]]
```

Works.

I think we need some tweaking. Ping @andrew2net .

**Comment by ronaldtse** [comment]
And we need to update README to indicate how to cite IEEE documents.

**Comment by andrew2net** [comment]
> And we need to update README to indicate how to cite IEEE documents.

@ronaldtse what do you mean? README contains examples of how to fetch documents. The reference `IEEE Std 1619-2007` is incorrect.

**Comment by ronaldtse** [comment]
`IEEE Std 1619-2007` is also how IEEE refers to their own documents, so we should support this syntax:

https://ieeexplore.ieee.org/document/4493450
<img width="657" alt="Screen Shot 2020-12-16 at 11 55 25 PM" src="https://user-images.githubusercontent.com/11865/102372455-2b8d8180-3ffa-11eb-8bf2-31cbb19d98d9.png">

https://ieeexplore.ieee.org/document/8637988
<img width="956" alt="Screen Shot 2020-12-16 at 11 58 15 PM" src="https://user-images.githubusercontent.com/11865/102372956-ad7daa80-3ffa-11eb-88b6-345617218fb5.png">

It seems that they have these patterns:

* "IEEE Std 1619-2007"
* "IEEE Std 1609.2b-2019 (Amendment to IEEE Std 1609.2-2016)"

We need to find out all document identifier formats from IEEE.

**Comment by andrew2net** [comment]
@ronaldtse I see. Now we use thie https://standards.ieee.org/search-results.html?q=1619-2007 edpoint to fetch references. It doesn't accept references like "IEEE Std 1619-2007". It accepts references like "IEEE 1619-2007" only.
The enpoint https://ieeexplore.ieee.org/search/searchresult.jsp accepts both format.
Seems we need to rewrite scrapper to use the new endpoint.

**Comment by ronaldtse** [comment]
@andrew2net The ieeexplore endpoint seems really slow. I think we just need to "drop" the "Std" name from our search at standards.ieee.org?

IEEE Xplore also provides journal articles other than standards, which do not use the IEEE SA (standards) bib-format. So we need to be careful here. In the future we may want to allow citing journals like the ones provided by IEEE.

**Comment by ronaldtse** [comment]
Maybe Xplore does work too:
https://ieeexplore.ieee.org/search/searchresult.jsp?queryText=1619&highlight=true&returnFacets=ALL&returnType=SEARCH&matchPubs=true&refinements=ContentType:Standards

<img width="578" alt="Screen Shot 2020-12-17 at 3 03 21 AM" src="https://user-images.githubusercontent.com/11865/102394245-6c928f80-4014-11eb-8081-9e28d8401107.png">

And we can also see the other document identifiers:

<img width="569" alt="Screen Shot 2020-12-17 at 3 03 30 AM" src="https://user-images.githubusercontent.com/11865/102394261-73b99d80-4014-11eb-8fef-e956b85929fb.png">
