### ISSUE TITLE
Review IEEE data format

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ieee#9]
https://github.com/ietf-ribose/bibxml-data-ieee/issues/3

**Comment by ronaldtse** [comment]
@andrew2net I see, then the RelatonIeee model should inherit from the StandardBibData model from Metanorma

<img width="415" alt="Screenshot 2021-10-31 at 7 59 02 AM" src="https://user-images.githubusercontent.com/11865/139561536-7ab05e9a-63d8-46b3-bdea-ef6bc5df7f3b.png">

**Comment by andrew2net** [comment]
@ronaldtse can we close this?

**Comment by ronaldtse** [comment]
Thanks @andrew2net !
